modLoader = "javafml"
loaderVersion = "[46,)"
license = "LGPLv3"

[[mods]]
modId = "forgematica"
version = "0.1.3-mc1.20.1"
displayName = "Forgematica"
displayURL="https://github.com/ThinkingStudios/Litematica-Forge" #optional
logoFile="icon.png" #optional
credits="masa" #optional
authors="TexTrue, ThinkingStudio" #optional
description = '''
Litematica unofficial forge port.

A modern schematic mod for Forge.
'''

[[dependencies.forgematica]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.forgematica]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.forgematica]]
modId = "mafglib"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "BOTH"
